### ISSUE TITLE
Tasks

### ISSUE THREAD

**Issue by Timur-Ionov** [bmstu-iu9/utp2020-7-paint#1]
* [x] Создать пустой canvas 
* [x] Разметить страницу для холста и кнопок
* [x] Добавить пустые css и js файлы

**Comment by Mazdaywik** [comment]
Отредактировал топик — сделал список с галочками:
```Markdown
* [ ] Создать пустой canvas 
* [ ] Разметить страницу для холста и кнопок
* [ ] Добавить пустые css и js файлы
```

**Comment by Timur-Ionov** [comment]
Спасибо, я исправил все остальные



Отправлено из мобильной Почты Mail.ru


среда, 8 июля 2020 г., 14:16 +0300 от notifications@github.com  <notifications@github.com>:
