### ISSUE TITLE
Фикс работы со слоями, рукой, фигурами.

### ISSUE THREAD

**Issue by sir-timio** [bmstu-iu9/utp2020-7-paint#108]
Исправить : 
 1. * [x] Рука перетаскивает слои по отдельности.
 2. * [x] Инструменты рисуют некорректно при перетаскивании, происходит смещение.
 3. * [x]  Работа руки при выходе за грань страницы. Без нажатия инструмент в режиме 'grabbing'.
 4. * [x] Корректная работа на следующем слое лишь при наличии следов работы на первом. 
5. * [x] При покидании мыши холста, регулировка фигур работает некорректно.
6. * [x] Пипетка забирает цвет только с текущего слоя.
7. * [x] Undo/redo работает только на текущем слое. 

Если берете на себя задачу, пишите в комменты ее номер

**Comment by alina-torr** [comment]
в процессе фикса 4-ого пункта, 2-ой тоже был исправлен

**Comment by Timur-Ionov** [comment]
Request  @alina-torr fix 0. bug too.
