### ISSUE TITLE
Работа со слоями.

### ISSUE THREAD

**Issue by sir-timio** [bmstu-iu9/utp2020-7-paint#118]
* [ ] Добавить функцию 'замок', которая запрещает/разрешает редактирование определенного слоя.
* [x] Добавить функцию 'глаз', которая показывает/скрывает определенный слой.

**Comment by Perpure** [comment]
![NDadO8vDZG8](https://user-images.githubusercontent.com/24734435/88916855-79823280-d26f-11ea-92dc-1b0a53e24687.jpg)
![ZuUxjU-A00c](https://user-images.githubusercontent.com/24734435/88916862-7be48c80-d26f-11ea-88b2-35796a1cc715.jpg)
@Mazdaywik ?

**Comment by sir-timio** [comment]
Closed via #136
