### ISSUE TITLE
Удалить .DS_Store

### ISSUE THREAD

**Issue by Mazdaywik** [bmstu-iu9/utp2020-7-paint#125]
В репозиторий накоммитили `.DS_Store` — файлы со служебными данными macOS. Это мусор. Во-первых, на других ОС в нём смысла нет. Во-вторых, при изменении исходников в рабочем каталоге могут обновляться служебные данные в `.DS_Store` и этот файл будет светиться как изменённый в выводе `git status`, что тоже некрасиво.

Для удаления всех `.DS_Store` можно использовать следующие команды:
* на Windows:
  ```Batch
  for /r %f in (*.DS_Store) do git rm %f
  echo .DS_Store>>.gitignore

  git checkout -b remove-ds-store
  git add .gitignore
  git commit -m "Удалены .DS_Store (#11)"
  git push -u origin remove-ds-store
  ```
* на unix-like:
  ```Bash
  find -name .DS_Store -exec git rm {} \;
  echo .DS_Store>>.gitignore

  git checkout -b remove-ds-store
  git add .gitignore
  git commit -m "Удалены .DS_Store (#11)"
  git push -u origin remove-ds-store
  ```

Предложенные выше команды добавят также `.DS_Store` в `.gitignore` и отправят новую ветку на сервер. А дальше pull request и вливание.

**Comment by sir-timio** [comment]
Спасибо, все исправлено
