### ISSUE TITLE
Валидация введенных данных.

### ISSUE THREAD

**Issue by sir-timio** [bmstu-iu9/utp2020-7-paint#79]
* [x] Валидация введенных размеров, возможность гибко устанавливать параметры.

**Comment by Mazdaywik** [comment]
И по какой причине закрыто?

**Comment by Timur-Ionov** [comment]
@Mazdaywik Здравствуйте, изначально стояла задача изменить файл, в котором была работа с введенными данными(tool-size). Я решил заодно написать функции, чтобы все могли использовать для проверки введенных значений. После консультации и моих советов автор файла tool-size попросил сделать эту работу сам (#80 ), так как мы пришли к соглашению.
На данном этапе у нас только два окна для ввода значений. Закрыл, потому что и работе над двумя этими окнами будет проверка и мои действия на данный этап чрезмерны, но я планирую стандартизировать работу с пользователем по необходимости, мы пока решаем, какие еще будут окна ввода.

**Comment by Mazdaywik** [comment]
Не, просто закрывать без комментариев задачу как-то странно. Или должны быть коммиты, привязанные к задаче — тогда понятно, что именно они её решили. Или привязанный pull request, или комментарий, почему закрыли. Либо можно повесить метку _invalid_ или _wontfix._ Только по этому я спросил.

**Comment by Timur-Ionov** [comment]
А, понял, учту.

**Comment by Timur-Ionov** [comment]
Ожидается решение задачи #89 (Дизайн).
