### ISSUE TITLE
Разработка логотипа.

### ISSUE THREAD

**Issue by sir-timio** [bmstu-iu9/utp2020-7-paint#86]
# необязательно
Логотип для редактора imago.
Принимаются любые идеи. Пожелания к стилю, ключевые слова : 
- минимализм, 
- бабочка(имаго - взрослая стадия насекомого в т.ч.), 
- простые фигуры,
- образ, портрет (imago - образ с латыни)
Примеры : 
![image](https://user-images.githubusercontent.com/67893803/87880782-30bfb380-c9fd-11ea-8710-84e73d5af0dc.png)
![image](https://user-images.githubusercontent.com/67893803/87880786-3d440c00-c9fd-11ea-90f3-d10dfd64a1ff.png)
![image](https://user-images.githubusercontent.com/67893803/87880792-564cbd00-c9fd-11ea-82d1-4c7094659d74.png)

![image](https://user-images.githubusercontent.com/67893803/87880814-78ded600-c9fd-11ea-8be6-568fddb086ea.png)
![image](https://user-images.githubusercontent.com/67893803/87925101-7b3a4200-ca88-11ea-8c22-6bf31e7ece60.png)

**Comment by Timur-Ionov** [comment]
Разработка логотипа будет уместна после определения дизайна меню приложения, поскольку точного плана еще нет.

**Comment by sir-timio** [comment]
Логотип есть

**Comment by Mazdaywik** [comment]
Если логотип не был нарисован в редакторе IMAGO, то он не труЪ.

**Comment by sir-timio** [comment]
@Mazdaywik Наша команда поддерживает философию догфуддинга, но, к сожалению, у нас не векторный редактор. В векторном мы бы спокойно все сделали сами. Зато, некоторые курсоры действительно будут 'наши')

**Comment by Mazdaywik** [comment]
Смайлик у меня намекал на иронию. А то, что курсоры будут «ваши» — это здорово!

**Comment by Zyxkim** [comment]
@Mazdaywik К сожалению, пока что логотипы в Imago мы делать не умеем, однако баннеры уже реально нарисовать.
![banner_imago](https://user-images.githubusercontent.com/54675260/89100275-841f0200-d3fe-11ea-961d-e2d89d77dffd.png)
![banner_free_imago](https://user-images.githubusercontent.com/54675260/89100276-84b79880-d3fe-11ea-96c8-7223e077e5d5.png)
