### ISSUE TITLE
Фикс кистей и возвращение базовой.

### ISSUE THREAD

**Issue by Timur-Ionov** [bmstu-iu9/utp2020-7-paint#97]
* [ ] Вернуть базовую кисть, поскольку она более не копирует карандаш. Карандаш будет наделен своими особенностями. 
* [ ] Установить размер инструмента в 1 px при клике на скетч кисть.
* [ ] Фикс мягкой кисти при использовании undo/redo.

**Comment by Mazdaywik** [comment]
А кто галочки будет ставить? 😃
